# Generated by Django 6.0.4 on 2026-04-22 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analyticsevent',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=120, null=True),
        ),
    ]
